Repository Kernel360/KDEV4-JoonggaeMoa-FE, pull requests merged in 2025-05, with the labels that each got.

#162 [#155] FEATURE: 알림 수정
  src/components/Layout.tsx
  src/context/NotificationContext.tsx
  src/main.tsx
  src/pages/Login.tsx
Labels: 🐞 Fix

#165 [#164] FEATURE: 엑셀 입력 형식, 예외처리 추가
  src/pages/CustomerImport.tsx
Labels: ✨ Feature

#166 [#163] REFACTOR: dto 수정
  src/components/Layout.tsx
  src/pages/ConsultationDetail.tsx
  src/pages/ConsultationList.tsx
  src/pages/ContractCreate.tsx
  src/pages/CustomerDetail.tsx
  src/pages/CustomerEdit.tsx
  src/pages/CustomerManagement.tsx
  src/pages/Dashboard.tsx
  src/pages/InquiryBoard.tsx
  src/pages/InquiryDetail.tsx
  src/pages/MessageCreate.tsx
  src/pages/SurveyAnswers.tsx
  src/pages/SurveyDetail.tsx
  src/pages/SurveyEdit.tsx
  src/pages/SurveyList.tsx
  src/pages/SurveySubmit.tsx
  src/services/agentService.ts
  src/services/consultationApi.ts
  src/services/contract.ts
  src/services/contractApi.ts
  src/services/customerApi.ts
  src/services/surveyApi.ts
  src/types/consultation.ts
  src/types/contract.ts
  src/types/customer.ts
  src/types/inquiry.ts
  src/types/survey.ts
Labels: 🔨 Refactor

#168 [#167] REFACTOR: 페이지네이션 리팩토링
  src/pages/ConsultationList.tsx
  src/pages/ContractCreate.tsx
  src/pages/ContractList.tsx
  src/pages/CustomerManagement.tsx
  src/pages/MessageCreate.tsx
  src/pages/MessageList.tsx
  src/pages/SurveyList.tsx
  src/services/contractApi.ts
  src/services/customerApi.ts
  src/services/messageApi.ts
  src/types/page.ts
Labels: 🔨 Refactor

#169 [#154] FIX: 지도 화면에 맞춘 매물 조회 가능
  src/components/ArticleDetail.tsx
  src/components/ArticleImage.tsx
  src/components/ArticleItem.tsx
  src/components/ArticleListFilter.tsx
  src/components/ArticleListMap.tsx
  src/components/ArticleListView.tsx
  src/components/ArticlePrice.tsx
  src/components/ArticleTypeBadge.tsx
  src/components/Layout.tsx
  src/components/MapView.tsx
  src/components/RegionSelector.tsx
  src/constants/articleConstants.ts
  src/constants/mapConstants.ts
  src/pages/ArticleList.tsx
  src/services/api.ts
  src/services/articleApi.ts
  src/services/regionApi.ts
  src/types/article.ts
  src/utils/articleDisplay.ts
  src/utils/articleFormat.ts
  src/utils/articlePrice.ts
  src/utils/articleUtils.ts
  src/utils/clusterUtils.ts
Labels: 🐞 Fix, 🎨 Html&css

#171 [#170] FIX: 클러스터 필터링 로직 추가 및 검색 타입 결정 기능 구현
  src/components/MapView.tsx
  src/pages/ArticleList.tsx
  src/services/articleApi.ts
  src/types/article.ts
Labels: 🐞 Fix

#173 [#155] FIX: 알림 오류 수정
  src/components/Layout.tsx
  src/components/ProtectedRoute.tsx
  src/context/NotificationContext.tsx
Labels: 🐞 Fix

#174 [#155] FIX: 알림 connection 변경
  src/context/NotificationContext.tsx
Labels: 🐞 Fix

#176 [#175] FIX: 토큰 재발급 로직 수정
  src/services/api.ts
Labels: 🐞 Fix

#181 [#180] FIX: CustomerAdd 및 CustomerImport 컴포넌트에서 응답 에러 코드의 타입을 문자열에서 숫자로 변경
  src/domain/customer/pages/CustomerAdd.tsx
  src/domain/customer/pages/CustomerImport.tsx
Labels: 🐞 Fix

#183 [#182] FIX: 배포 오류 수정
  index.html
  public/logo.png
  public/배경없는 로고.ico
  src/domain/article/map/hooks/useMarkers.ts
  src/domain/inquiry/pages/InquiryBoard.tsx
  src/domain/inquiry/pages/InquiryDetail.tsx
  src/global/auth/pages/Login.tsx
  src/global/auth/pages/SignUp.tsx
  src/global/common/components/Layout.tsx
  vite.config.ts
Labels: 🐞 Fix

#187 [#186] DOC: README.md 수정
  README.md
Labels: 📃 Docs

#188 [#186] DOC: README.md 수정
  README.md
Labels: 📃 Docs
