Repository Kernel360/KDEV4-JoonggaeMoa-FE, pull requests merged in 2025-04, with the labels that each got.

#21 [#18] REFACTOR: 환경변수 관리
  .gitignore
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/services/api.ts
  tsconfig.json
Labels: 🔨 Refactor

#24 [#23] FEATURE: 고객 관리 - 엑셀 다운로드 기능 추가 및 화면 리팩토링
  src/pages/CustomerDetail.tsx
  src/pages/CustomerImport.tsx
  src/pages/CustomerManagement.tsx
  src/services/customerApi.ts
Labels: ✨ Feature, 🔨 Refactor

#26 [#25] FEATURE: 고객 정보 등록 화면 리팩토링
  package-lock.json
  package.json
  src/pages/CustomerAdd.tsx
Labels: 🔨 Refactor

#30 [#29] FIX: 계약 관리 페이지 api 연동 수정
  index.html
  src/pages/ContractDetail.tsx
  src/pages/ContractList.tsx
  src/types/contract.ts
Labels: 🐞 Fix

#37 [#32] FIX: 새로고침 시 로그인 상태 유지
  src/components/ProtectedRoute.tsx
  src/context/AuthContext.tsx
Labels: 🐞 Fix

#31 [#22] FIX: 문자api, 문자 템플릿 api 수정
  src/App.tsx
  src/pages/MessageCreate.tsx
  src/pages/MessageDetail.tsx
  src/pages/MessageHistory.tsx
  src/pages/MessageList.tsx
  src/pages/MessageTemplateCreate.tsx
  src/pages/MessageTemplateList.tsx
  src/services/messageApi.ts
  src/services/messageTemplateApi.ts
  src/types/message.ts
Labels: 🐞 Fix

#34 [#33] FEAT: 중개사 마이페이지 구현
  src/App.tsx
  src/pages/Dashboard.tsx
  src/pages/MyPage.tsx
  src/services/agentService.ts
Labels: ✨ Feature

#36 [#35] FIX: 대시보드 ui 수정
  src/pages/Dashboard.tsx
Labels: 🎨 Html&css

#39 [#28] REFACTOR: 상담 관리 페이지 수정
  package-lock.json
  package.json
  src/pages/ConsultationHistory.tsx
  src/pages/ConsultationList.tsx
  src/services/consultation.ts
  src/services/consultationApi.ts
  src/types/consultation.ts
Labels: 🔨 Refactor

#42 [#40] FIX: 고객 등록, 수정 유효성 검사 수정
  src/pages/CustomerAdd.tsx
  src/pages/CustomerEdit.tsx
Labels: 🐞 Fix

#43 [#41] FIX: 계약 등록 유효성 검사 추가
  src/pages/ContractCreate.tsx
Labels: 🐞 Fix

#44 [#38] FEAT: 회원가입 ui 수정
  src/App.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/pages/SignUp.tsx
Labels: ✨ Feature

#45 [#28] REFACTOR: status-inform api와 dateCount api를 하나의 api로 변경
  src/pages/ConsultationList.tsx
  src/services/consultationApi.ts
  src/types/consultation.ts
Labels: 🔨 Refactor

#49 [#48] FIX: 회원가입 중복검증 수정
  src/App.tsx
  src/pages/ConsultationHistory.tsx
  src/pages/SignUp.tsx
Labels: 🐞 Fix

#53 [#52] FEAT: 매물 관리 페이지
  package-lock.json
  package.json
  src/App.tsx
  src/pages/ArticleList.tsx
  src/pages/Dashboard.tsx
  src/services/articleApi.ts
  src/types/article.ts
Labels: ✨ Feature

#56 [#55] FIX: 문자 api uri 수정
  src/pages/MessageCreate.tsx
  src/pages/SignUp.tsx
  src/services/messageApi.ts
Labels: 🐞 Fix

#58 [#57] FIX: survey page 수정
  src/pages/MessageCreate.tsx
  src/pages/SurveyAnswers.tsx
  src/pages/SurveyCreate.tsx
  src/pages/SurveyDetail.tsx
  src/pages/SurveyEdit.tsx
  src/pages/SurveyList.tsx
  src/pages/SurveySubmit.tsx
  src/services/surveyApi.ts
  src/types/survey.ts
Labels: 🐞 Fix

#62 [#61] FIX: 설문 주소 복사 오류 수정
  src/pages/SurveyDetail.tsx
Labels: 🐞 Fix

#64 [#63] FEATURE: 푸시 알림 기능 추가
  package-lock.json
  package.json
  src/App.tsx
  src/context/AuthContext.tsx
  src/pages/Dashboard.tsx
  src/utils/notificationUtils.ts
Labels: ✨ Feature

#65 [#60] FEAT: 대시보드 페이지 데이터 출력
  package-lock.json
  package.json
  src/pages/Dashboard.tsx
  src/services/dashboardApi.ts
  src/types/dashboard.ts
Labels: ✨ Feature

#68 [#66] FEAT: 모든 페이지에 UI 배너 추가
  src/App.tsx
  src/components/Layout.tsx
  src/components/ProtectedRoute.tsx
  src/pages/ArticleList.tsx
  src/pages/ConsultationDetail.tsx
  src/pages/ConsultationEdit.tsx
  src/pages/ConsultationList.tsx
  src/pages/ContractCreate.tsx
  src/pages/ContractDetail.tsx
  src/pages/ContractEdit.tsx
  src/pages/ContractList.tsx
  src/pages/CustomerAdd.tsx
  src/pages/CustomerDetail.tsx
  src/pages/CustomerEdit.tsx
  src/pages/CustomerImport.tsx
  src/pages/CustomerManagement.tsx
  src/pages/Dashboard.tsx
  src/pages/MessageCreate.tsx
  src/pages/MessageHistory.tsx
  src/pages/MessageList.tsx
  src/pages/MessageTemplateCreate.tsx
  src/pages/MessageTemplateList.tsx
  src/pages/SurveyAnswers.tsx
  src/pages/SurveyCreate.tsx
  src/pages/SurveyDetail.tsx
  src/pages/SurveyEdit.tsx
  src/pages/SurveyList.tsx
  src/types/consultation.ts
  src/utils/dateUtils.ts
Labels: ✨ Feature

#70 [#97] FEAT: 매물 페이지 상세 정보 수정
  index.html
  src/pages/ArticleList.tsx
  src/types/article.ts
  src/types/kakao-maps.d.ts
  vite.config.ts
Labels: ❗ Bug

#73 [#72] FIX: 문자 에러 수정
  src/pages/MessageCreate.tsx
  src/pages/MessageDetail.tsx
  src/pages/MessageHistory.tsx
  src/pages/MessageList.tsx
  src/pages/MessageTemplateCreate.tsx
  src/pages/MessageTemplateList.tsx
  src/services/messageApi.ts
Labels: 🐞 Fix

#76 FEAT: 매물관리 페이지 레이아웃 개선
  src/pages/ArticleList.tsx
  src/services/regionApi.ts
  src/types/article.ts
Labels: 🐞 Fix

#80 [#79] FIX: 계약 오류 수정
  src/App.tsx
  src/pages/ContractCreate.tsx
  src/pages/ContractDetail.tsx
  src/pages/ContractEdit.tsx
  src/pages/ContractList.tsx
  src/services/contractApi.ts
  src/types/contract.ts
Labels: 🐞 Fix

#81 [#78] FEAT: 설문 오류 수정
  src/pages/SurveyAnswers.tsx
  src/pages/SurveyCreate.tsx
  src/pages/SurveyDetail.tsx
  src/pages/SurveyEdit.tsx
  src/pages/SurveyList.tsx
  src/pages/SurveySubmit.tsx
  src/types/survey.ts
Labels: 🐞 Fix

#85 [#82] FIX: 고객 오류 수정
  src/pages/CustomerAdd.tsx
  src/pages/CustomerEdit.tsx
Labels: 🐞 Fix

#84 [#83] REMOVE: 페이지 이동 시 딜레이 삭제
  src/pages/ConsultationEdit.tsx
  src/pages/ContractCreate.tsx
  src/pages/ContractDetail.tsx
  src/pages/CustomerAdd.tsx
  src/pages/CustomerDetail.tsx
  src/pages/CustomerEdit.tsx
  src/pages/CustomerImport.tsx
  src/pages/MessageCreate.tsx
  src/pages/MessageDetail.tsx
  src/pages/SignUp.tsx
  src/pages/SurveyCreate.tsx
  src/pages/SurveyDetail.tsx
  src/pages/SurveyEdit.tsx
Labels: 🐞 Fix

#87 [#86] FEATURE: agent 기능 추가
  src/pages/MyPage.tsx
  src/pages/SignUp.tsx
Labels: ✨ Feature

#89 [#88] FIX: 매물 관리 페이지 검색창 수정
  src/pages/ArticleList.tsx
Labels: 🐞 Fix

#91 [#90] FIX: 빌드 오류 수정
  src/App.tsx
Labels: 🐞 Fix

#93 [#92] FIX: 화면 오류 수정
  src/pages/MyPage.tsx
Labels: 🐞 Fix

#94 [#92] FIX: 프론트 화면 오류 수정
  src/pages/CustomerManagement.tsx
  src/pages/Dashboard.tsx
  src/pages/MessageHistory.tsx
  src/pages/MessageList.tsx
  src/pages/SurveyAnswers.tsx
Labels: 🐞 Fix

#97 [#96] FEATURE: 매물 지도 구현 및 구성 요소 리팩토링
  index.html
  src/components/ArticleDetail.tsx
  src/components/ArticleItem.tsx
  src/components/article/ArticleImage.tsx
  src/components/article/ArticlePrice.tsx
  src/components/article/ArticleTypeBadge.tsx
  src/components/map/MapView.tsx
  src/components/map/MarkerPopup.tsx
  src/components/region/RegionSelector.tsx
  src/pages/ArticleList.tsx
  src/pages/Login.tsx
  src/services/api.ts
  src/services/articleApi.ts
  src/services/regionApi.ts
  src/types/article.ts
  src/types/kakao-maps.d.ts
  src/types/kakao.d.ts
  src/utils/articleUtils.ts
  src/utils/regions/regionUtils.ts
Labels: ✨ Feature, 🔨 Refactor

#99 [#98] FIX: 날짜 양식 변경
  src/pages/MessageDetail.tsx
  src/pages/MessageHistory.tsx
  src/pages/MessageList.tsx
  src/pages/SurveyAnswers.tsx
  src/pages/SurveyDetail.tsx
  src/pages/SurveyList.tsx
  src/types/message.ts
  src/types/survey.ts
Labels: 🐞 Fix

#100 [#46] FEATURE: update 빈 값 처리
  src/pages/SurveyEdit.tsx
Labels: ✨ Feature

#103 [#101] FEATURE: 알림 기능
  src/App.tsx
  src/components/Layout.tsx
  src/context/NotificationContext.tsx
  src/pages/Login.tsx
  src/pages/NotificationList.tsx
Labels: ✨ Feature

#105 [#102] FEAT : 상담 히스토리 api
  src/App.tsx
  src/pages/ConsultationDetail.tsx
  src/pages/ConsultationList.tsx
  src/pages/CustomerDetail.tsx
  src/services/consultationApi.ts
  src/types/consultation.ts
  src/types/customer.ts
Labels: ✨ Feature

#107 [#104] Feature: 대시보드 계약 만료일 추가
  src/pages/Dashboard.tsx
Labels: ✨ Feature

#109 [#108] FIX: 계약 - createdAt을 모두 startedAt으로 수정
  src/pages/ContractCreate.tsx
  src/pages/ContractDetail.tsx
  src/pages/ContractList.tsx
  src/types/contract.ts
Labels: 🐞 Fix

#110 [#106] FEAT: 고객 히스토리 뷰
  package-lock.json
  package.json
  src/App.tsx
  src/pages/ConsultationDetail.tsx
  src/pages/ConsultationEdit.tsx
  src/pages/ConsultationList.tsx
  src/pages/CustomerAdd.tsx
  src/pages/CustomerDetail.tsx
  src/pages/CustomerEdit.tsx
  src/services/customerApi.ts
  src/types/consultation.ts
  src/types/customer.ts
  tsconfig.json
Labels: ✨ Feature

#113 [#112] FEAT: 로고 적용
  index.html
  public/로고.ico
  public/배경없는 로고.ico
  src/components/Layout.tsx
Labels: 🎨 Html&css

#115 [#114] FIX: 상담 리스트에서 상태 변경 구현
  src/pages/ConsultationDetail.tsx
  src/pages/ConsultationList.tsx
Labels: 🐞 Fix

#116 [#111] FEATURE: 고객 문의 게시판
  package-lock.json
  package.json
  src/App.tsx
  src/components/Layout.tsx
  src/pages/InquiryBoard.tsx
  src/pages/InquiryDetail.tsx
  src/types/inquiry.ts
Labels: ✨ Feature

#119 Feature-118-매물-지도-개선
  .gitignore
  src/components/ArticleDetail.tsx
  src/components/ArticleItem.tsx
  src/components/article/ArticleImage.tsx
  src/components/article/ArticlePrice.tsx
  src/components/article/ArticleTypeBadge.tsx
  src/components/map/MapView.tsx
  src/components/map/MarkerPopup.tsx
  src/pages/ArticleList.tsx
  src/services/articleApi.ts
  src/types/article.ts
  src/types/kakao.d.ts
  src/utils/articleUtils.ts
Labels: ✨ Feature, 🐞 Fix, 🎨 Html&css, 🔨 Refactor

#121 [#111] FIX: 문의게시판 uri 링크 수정
  src/pages/InquiryDetail.tsx
Labels: 🐞 Fix

#122 [#117] FIX: UI 수정
  package-lock.json
  package.json
  public/로고.ico
  public/로고.png
  src/App.tsx
  src/components/Layout.tsx
  src/pages/ConsultationDetail.tsx
  src/pages/ConsultationList.tsx
  src/pages/ContractCreate.tsx
  src/pages/ContractDetail.tsx
  src/pages/ContractList.tsx
  src/pages/CustomerAdd.tsx
  src/pages/CustomerDetail.tsx
  src/pages/CustomerEdit.tsx
  src/pages/CustomerImport.tsx
  src/pages/CustomerManagement.tsx
  src/pages/Dashboard.tsx
  src/pages/Login.tsx
  src/pages/MessageCreate.tsx
  src/pages/MessageDetail.tsx
  src/pages/MessageHistory.tsx
  src/pages/MessageList.tsx
  src/pages/MessageTemplateCreate.tsx
  src/pages/MyPage.tsx
  src/pages/SignUp.tsx
  src/pages/SurveyAnswers.tsx
  src/pages/SurveyCreate.tsx
  src/pages/SurveyEdit.tsx
  src/pages/SurveyList.tsx
  src/services/customerApi.ts
Labels: 🎨 Html&css

#125 [#124] FEATURE: 문의게시판 - chatbot 추가
  src/components/ChatbotDialog.tsx
  src/pages/InquiryBoard.tsx
Labels: ✨ Feature

#128 [#127] FIX: 매물 빌드 오류 수정
  src/components/article/ArticlePrice.tsx
  src/types/article.ts
Labels: 🐞 Fix

#129 [#126] FIX: 문의 게시판 ui 수정
  index.html
  src/components/Layout.tsx
  src/pages/InquiryBoard.tsx
  src/pages/InquiryDetail.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
Labels: 🎨 Html&css

#131 [#130] FIX: App.tsx 알림 수정
  src/App.tsx
Labels: 🐞 Fix

#133 [#132] FIX: QA 중 수정
  src/App.tsx
  src/context/NotificationContext.tsx
  src/pages/ArticleList.tsx
  src/pages/ConsultationList.tsx
  src/pages/ContractList.tsx
  src/pages/CustomerManagement.tsx
  src/pages/Dashboard.tsx
  src/pages/InquiryBoard.tsx
  src/pages/InquiryDetail.tsx
  src/pages/Login.tsx
  src/pages/MessageList.tsx
  src/pages/SurveyList.tsx
Labels: 🐞 Fix

#139 #[138] FIX : 답변 url 수정
  src/pages/InquiryDetail.tsx
Labels: 🐞 Fix

#141 [#137] REFACTOR: QA fix
  src/App.tsx
  src/components/Layout.tsx
  src/components/ProtectedRoute.tsx
  src/pages/ConsultationDetail.tsx
  src/pages/ConsultationList.tsx
  src/pages/ContractCreate.tsx
  src/pages/Dashboard.tsx
  src/pages/InquiryBoard.tsx
  src/pages/InquiryDetail.tsx
  src/pages/MessageCreate.tsx
  src/pages/SurveySubmit.tsx
Labels: 🔨 Refactor

#142 [#135] FEAT: 매물 정렬 및 필터 구현
  src/components/ArticleDetail.tsx
  src/components/map/MapView.tsx
  src/pages/ArticleList.tsx
  src/services/articleApi.ts
  src/services/regionApi.ts
Labels: ✨ Feature, 🎨 Html&css

#143 [#140] FIX: 매물 통계 dto 수정
  src/pages/Dashboard.tsx
  src/services/dashboardApi.ts
  src/types/dashboard.ts
Labels: 🐞 Fix

#148 [#146] FIX: footer 수정
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/pages/ArticleList.tsx
  src/pages/ConsultationList.tsx
  src/pages/ContractCreate.tsx
  src/pages/ContractDetail.tsx
  src/pages/ContractList.tsx
  src/pages/CustomerAdd.tsx
  src/pages/CustomerEdit.tsx
  src/pages/CustomerImport.tsx
  src/pages/CustomerManagement.tsx
  src/pages/Dashboard.tsx
  src/pages/InquiryBoard.tsx
  src/pages/MessageCreate.tsx
  src/pages/MessageList.tsx
  src/pages/MessageTemplateCreate.tsx
  src/pages/SurveyAnswers.tsx
  src/pages/SurveyCreate.tsx
  src/pages/SurveyDetail.tsx
  src/pages/SurveyEdit.tsx
  src/pages/SurveyList.tsx
  src/theme.ts
Labels: 🐞 Fix

#149 [#147] FIX: 스타일 수정 및 ArticleDetail 컴포넌트 리팩토링
  src/App.css
  src/components/ArticleDetail.tsx
  src/components/ArticleImage.tsx
  src/components/ArticleItem.tsx
  src/components/ArticlePrice.tsx
  src/components/ArticleTypeBadge.tsx
  src/components/MapView.tsx
  src/components/RegionSelector.tsx
  src/components/map/MapView.tsx
  src/components/map/MarkerPopup.tsx
  src/pages/ArticleList.tsx
  src/types/article.ts
  src/utils/articleUtils.ts
  src/utils/regionData.ts
  src/utils/regionUtils.ts
Labels: 🐞 Fix, 🎨 Html&css

#153 [#152] FIX: 피드백 수정
  src/pages/ConsultationDetail.tsx
  src/pages/MessageTemplateCreate.tsx
  src/pages/MyPage.tsx
Labels: 🐞 Fix

#158 [#155] REFACTOR: 알림 수정
  src/context/NotificationContext.tsx
Labels: 🔨 Refactor

#159 [#155] FIX: dashboard notification url 수정
  src/pages/Dashboard.tsx
Labels: 🐞 Fix

#161 [#160] FIX: get agent api 수정
  src/pages/Dashboard.tsx
Labels: 🐞 Fix
